#!/bin/bash

MIN_BRIGHTNESS=0
MAX_BRIGHTNESS=100
SCREEN=($(xrandr -q | grep ' connected' | head -n 1 | cut -d ' ' -f1))

sqlite3 brite.db <<EOF
CREATE TABLE IF NOT EXISTS record  (
  id INTEGER PRIMARY KEY,
  display TEXT NOT NULL,
  brightness NUMERIC NOT NULL
);
EOF

RECORD_COUNT=$(
sqlite3 brite.db <<EOF 
  SELECT COUNT(*) FROM record; 
EOF
)

if [ $RECORD_COUNT -eq 0 ]
then
  sqlite3 brite.db <<EOF
    INSERT INTO record (display, brightness)
    VALUES ("$SCREEN", 1);
EOF
fi

function GET_CURRENT_BRIGHTNESS() {
  local CURRENT_BRIGHTNESS=$(
sqlite3 brite.db <<EOF 
  SELECT brightness FROM record;
EOF
)
  echo $CURRENT_BRIGHTNESS
}

function SCREEN_CURRENT_BRIGHTNESS() {
  echo "$SCREEN is set to brightness $(GET_CURRENT_BRIGHTNESS)"
}

function UPDATE_BRIGHTNESS() {
    sqlite3 brite.db <<EOF
    UPDATE record
    SET brightness=$1
    WHERE display='$SCREEN';
EOF
}

function CHANGE_BRIGHTNESS() {
  xrandr --output $SCREEN --brightness $1
  UPDATE_BRIGHTNESS $1
}

function INCREMENT_BRIGHTNESS() {
  local CURRENT_BRIGHTNESS=$(GET_CURRENT_BRIGHTNESS)

  if [ $(echo "$CURRENT_BRIGHTNESS != $MAX_BRIGHTNESS" | bc) -eq 1 ]
  then
    local NEW_BRIGHTNESS="$(echo $CURRENT_BRIGHTNESS + '0.1' | bc)"
    CHANGE_BRIGHTNESS $NEW_BRIGHTNESS
  fi
}

function DECREMENT_BRIGHTNESS() {
  local CURRENT_BRIGHTNESS=$(GET_CURRENT_BRIGHTNESS)

  if [ $(echo "$CURRENT_BRIGHTNESS != $MIN_BRIGHTNESS" | bc) -eq 1 ]
  then
    local NEW_BRIGHTNESS="$(echo $CURRENT_BRIGHTNESS - '0.1' | bc)"
    CHANGE_BRIGHTNESS $NEW_BRIGHTNESS
  fi
}

function HELP() {
  printf "usage: brite [options]\n"
  printf "where options are:\n"
  printf "\t<value>\tset brightness to certain value\n"
  printf "\t-d\tdecrease brightness by 0.1\n"
  printf "\t-i\tincrease brightness by 0.1\n"
}

if [ $# -eq 0 ] 
then
  SCREEN_CURRENT_BRIGHTNESS
else
  ARG=$1
  HYPHEN_INDEX=`expr "$ARG" : '-'`

  if [ $HYPHEN_INDEX -eq 0 ]
  then
    CHANGE_BRIGHTNESS $ARG
  else
    while getopts "idh" opt
    do
      case $opt in
        i) INCREMENT_BRIGHTNESS ;;
        d) DECREMENT_BRIGHTNESS ;;
        h) HELP ;;
        ?)
          echo -e "Try 'brite -h' for more information."
          exit 1
      esac
    done
  fi
fi